### PR TITLE
Update strings_zh.txt

### PR DESCRIPTION
**Pull request by dunkeng**
Complement the translation and adjust part of the original translation to make it more in line with the simplified Chinese language habits. Is there a complete English document for reference?

### CODE REVIEW

**Comment by sylikc** [comment]
@dunkeng , thanks for the contribution.  I can merge and put out an updated release.

I think the only "complete" English document for reference is the English strings next to the translation line.  There's no _en string file by itself.

**Comment by sylikc** [comment]
closed via https://github.com/sylikc/jpegview/commit/77a459755a003384fe9b965f129275d4c2015877

**Comment by sylikc** [comment]
@dunkeng Hi, a new reference strings.txt is finally out, and I have updated with the reference... can you translate some of the new strings?

https://github.com/sylikc/jpegview/blob/master/src/JPEGView/Config/strings_zh.txt Look towards the bottom for the strings that still need translation.

Thanks!

**Comment by dunkeng** [comment]
> @dunkeng Hi, a new reference strings.txt is finally out, and I have updated with the reference... can you translate some of the new strings?
> 
> https://github.com/sylikc/jpegview/blob/master/src/JPEGView/Config/strings_zh.txt Look towards the bottom for the strings that still need translation.
> 
> Thanks!

@sylikc Hello, I have updated the translation, please review.

**Comment by sylikc** [comment]
> I found that the current translation item is not completely different from strings.txt. I will modify it again. I will resubmit it when it is finished.

I found a slight bug when merging the russian translation, so I found the full complete texts...

btw, you don't have to translate any of the instructions, that's just for you to read.  any comments at the bottom are automatically maintained by script now... so when translations are filled, they'll disappear at the next run.

Thanks!

**Pull request closed without merging**
