### PR TITLE
Update dcraw to the latest version (9.28.0)

### PR DESCRIPTION
**Pull request by doyaGu**
Just tested simply through viewing some RAW files, more tests are expected.

### CODE REVIEW

**Comment by sylikc** [comment]
I've been looking at the diff between the original dcraw version 8.86 and the one included with JPEGview which is named dcraw_mod.cpp ... I'm not sure why or the purpose of some of the changed / removed functionality.

Did you just drop in the file verbatim?

**Comment by doyaGu** [comment]
Not exactly, I just made similar changes that occur in the original dcraw_mod.cpp to the new version dcraw. It can be compiled and can work normally.

**Comment by sylikc** [comment]
I reviewed these changes... really awesome job taking in the latest dcraw with minimal changes.

I'm not yet entirely sure it's going to operate the same way, but to the least it compiles...  I tried making changes which matched the previous 8.86 diffs and failed miserably lol

**Comment by sylikc** [comment]
@doyaGu thank you VERY MUCH for the contribution.  You took the complex modifications in the original ```dcraw_mod.cpp``` and made it relatively simple to do future merges.

I took the modifications you made to the file and **reverted all the whitespace changes**.  While it uglified the code again, it should make future upstream merges much easier, since the diff is only a handful of lines, and only a few functions commented out, and **clearly shows the code that you put in**.

More testing will probably be needed by the general community, but I ran a few tests and it seems ok.

**Comment by doyaGu** [comment]
Got it.

**Pull request closed without merging**
