### PR TITLE
Automatically upload build artifacts for all versions

### PR DESCRIPTION
**Pull request by qbnu**

### CODE REVIEW

**Comment by sylikc** [comment]
i can put it into the pipeline if this works... I've been building manually but an automatic build and deploy seems like a great idea lol

**Comment by qbnu** [comment]
I actually meant to do this on my own fork lol. I'll reopen it.

**Comment by sylikc** [comment]
@qbnu I can't figure out where the output of the files are... where does it get uploaded to?

**Comment by qbnu** [comment]
They get saved as artifacts at the bottom of the summary pages
https://github.com/sylikc/jpegview/actions/runs/3805721313#artifacts

**Comment by sylikc** [comment]
oh cool.  It's like automatically building JPEGView nightlies

**Pull request merged**
