### PR TITLE
Animated AVIF

### PR DESCRIPTION
**Pull request by qbnu**
Adds support for animated AVIF with libavif. The 32-bit builds don't work and I'm not sure why. Some AVIFs can be decoded with libheif but not with libavif, so I added a fallback to it (see [this issue](https://github.com/AOMediaCodec/libavif/issues/714)). libheif should be rebuilt with dav1d as a DLL so it can be shared with libavif.

Test data:
- https://github.com/AOMediaCodec/libavif/tree/main/tests/data
- https://github.com/link-u/avif-sample-images
- http://download.opencontent.netflix.com/?prefix=AV1/Chimera/AVIF/
- https://github.com/test-images/avif

### CODE REVIEW

**Comment by sylikc** [comment]
Thanks!  I'll adjust the build scripts to add dav1d.dll back instead of having it statically built into libheif.

**Comment by sylikc** [comment]
I'm seeing a weird assertion failure in crt at delete[] when running 32-bit debug build... when leaving an AVIF image and moving onto something else... is that what you're seeing?
```c++
CJPEGImage::~CJPEGImage(void) {
	delete[] m_pOrigPixels;
```

```c++
    // If this assertion fails, a bad pointer has been passed in.  It may be
    // totally bogus, or it may have been allocated from another heap.  The
    // pointer must have been allocated from the CRT heap.
    _ASSERTE(_CrtIsValidHeapPointer(block));
```

In the release build, it just continues to work... probably just skipping over the bad block when freeing?

**Comment by sylikc** [comment]
As for the build error, I'm not sure what flags you used to build the libs/dlls, but I was able to rebuild it to get it working with win32 (minus the crash of course)

What was your process of building the avif lib/dll?

**Comment by sylikc** [comment]
can you shoot me an email (address on my profile)?  I wanted to ask some stuff offline :)  Thanks

**Comment by qbnu** [comment]
I updated all the libs and made avif a DLL. [This](https://github.com/qbnu/build-heif-avif-decoders) is what I used to build everything.
> I'm seeing a weird assertion failure in crt at delete[] when running 32-bit debug build... when leaving an AVIF image and moving onto something else... is that what you're seeing?

Not entirely sure why this happened but it's fixed by allocating memory ourselves instead of letting libavif do it.

**Comment by qbnu** [comment]
I realized JPEGView can now play most popular YouTube videos without re-encoding:
```
yt-dlp -f 395 https://www.youtube.com/watch?v=jNQXAC9IVRw -o me-at-the-zoo.mp4
ffmpeg -i me-at-the-zoo.mp4 -c copy me-at-the-zoo.avif
```
Then open.

**Comment by slovuj** [comment]
yt-dlp -f 395 https://www.youtube.com/watch?v=jNQXAC9IVRw -o me-at-the-zoo.mp4
ffmpeg -i me-at-the-zoo.mp4 -c copy me-at-the-zoo.avif

The above commands worked for me on Windows, but I guess I don't have the latest JPEGView to test it. So I opened with some other tools - is it normal that there is no sound?

**Comment by sylikc** [comment]
@qbnu should `avifs` be added to the extension list?  When I went to download samples that was the extension that the animated/sequence ones had, but I don't really see it referenced anywhere else

**Comment by sylikc** [comment]
i merged it first... figured we could have the extension discussion afterwards, since it's like a two line change

**Comment by qbnu** [comment]
> should `avifs` be added to the extension list?

This was was removed from the spec, see https://github.com/AOMediaCodec/av1-avif/pull/86

> the AOM official tech doc shows a filetype of avis

Refers to the brand, which we check for in bytes 8-11 of the file

**Comment by sylikc** [comment]
I figured it had to be something.  So Google's sample images were from in the early days.

**Pull request merged**
