### PR TITLE
Update strings_ja.txt

### PR DESCRIPTION
**Pull request by maboroshin**
Hello developer!

You will need to update the readme.html. I updated the Japanese translation in 2018. Then, I have read the readme.html and sent it to your Gmail. However, if you have not read the email and it is updated on Github. If so, revising readme.html is a good idea.

### CODE REVIEW

**Comment by sylikc** [comment]
Hi @maboroshin thanks for the translation!  I'll merge it into the next release.

I'm not the original author, but continuing his work.  Please send your email or post it up somewhere and I'll merge the readme.html.... I know it's certainly out of date

**Comment by maboroshin** [comment]
Thanks. Nice work.

In ```readme.html```, it says to send the translation file to the developer, not Github.
https://github.com/sylikc/jpegview/blob/master/JPEGView/Config/readme.html#L297

**Comment by sylikc** [comment]
> In `readme.html`, it says to send the translation file to the developer, not Github. https://github.com/sylikc/jpegview/blob/master/JPEGView/Config/readme.html#L297

Oh... ok.  I got it... this might be why I got an email for translation.  I have to update that... actual tbh, I haven't read through the whole readme myself haha.

**Comment by sylikc** [comment]
This is ready for merge?

**Comment by maboroshin** [comment]
Please merge. My translation is complete.

**Comment by sylikc** [comment]
merged.  Thanks for the contribution!

**Pull request merged**
