### PR TITLE
Add copy file path

### PR DESCRIPTION
**Pull request by kropptrevor**
Implements #36

In the right click menu:
> Copy to clipboard Ctrl+C
> Copy original size image Ctrl+X
> Copy file path
> Paste from clipboard Ctrl+V

I wasn't sure what the default key binding would be. Any suggestions?

### CODE REVIEW

**Comment by sylikc** [comment]
Interesting... I like this feature, and you've added it pretty cleanly

**Comment by Bobbsterman** [comment]
Nice!
I would go with some modification of C. E.g. Ctrl+Shift+C

**Comment by kropptrevor** [comment]
I've added a shortcut and an entry in the help screen. I did not provide translations, however.

**Comment by Bobbsterman** [comment]
Nice. Lets hope @sylikc finds time to pull some of these enhancements!

I can provide a French translation:
"copy image path to clipboard" = "copier l'emplacement de l'image"

**Comment by sylikc** [comment]
@Bobbsterman I'm merging this PR... the exact translation strings are right now are

"Copy file path of the image to clipboard"
and "Copy file path"

I'll roll them in when you translate.  Some of the translation stuff also needs to get cleaned up as per #105

**Comment by sylikc** [comment]
@kropptrevor thanks for the contribution.  This will likely end up being a feature I use almost daily!

Certainly was helpful to review your code, where I forgot to put help in my "Open containing folder in Explorer" feature, and forgot to disable it for clipboard images.  65e7905

FYI: I fixed the Russian translation file getting mangled and also the popup menu bug a326463

**Comment by kropptrevor** [comment]
That's good to hear. I'm happy to have contributed.

**Pull request merged**
