### PR TITLE
QOI (Quite OK Image) support

### PR DESCRIPTION
**Pull request by qbnu**
Encoding and decoding support.

[Website](https://qoiformat.org/)
[Reference implementation](https://github.com/phoboslab/qoi)
[Wikipedia article](https://en.wikipedia.org/wiki/QOI_(image_format))
[Test images](https://qoiformat.org/qoi_test_images.zip)

### CODE REVIEW

**Comment by sylikc** [comment]
wow cool, it writes too!

**Comment by sylikc** [comment]
Is there a DLL or LIB?  or is it all encapsulated in the QOIWrapper?

**Comment by sylikc** [comment]
Quick question, I figured I'd ask it here... I was trying to use `std::gcd` method call and it looks like it's only supported in C++17.  The JPEGview project is currently C++14... is there any drawback to moving to a later version of C++?  Will it affect your future code?

I can use the C++14 calling convention, but just wondering if there's any benefit/drawback to moving to later version of C++, or does it not matter?

**Comment by qbnu** [comment]
VS2017 doesn't support C++20, so it might affect Windows XP builds? Otherwise it should be fine.

**Pull request merged**
