### PR TITLE
Borderless window, click drag to move, always on top, selection mode disable

### PR DESCRIPTION
**Pull request by sylikc**
New feature: ALT+CLICK drag to move
New feature: borderless window (no title bar)

The borderless window is a bit glitchy right now.  It works, but when drawing, JPEGView doesn't take into account the new dimensions yet.

Addresses #5 #75

### CODE REVIEW

**Comment by sylikc** [comment]
To move the window at any time, **ALT+CLICK and drag**.  To toggle from borderless to not borderless, **ALT+MIDDLECLICK**

Currently the redraw logic isn't quite where I want it to be... but the feature mostly works

**Comment by c-sanchez** [comment]
Hi @sylikc, thank you very much for everything you do with jpegview, you have managed to include the improvements that were needed.

Unfortunately the click of the central wheel of my mouse does not work, so I cannot test the function at the moment.

If you can add some workaround to change from borderless to not borderless that will be nice.
Maybe some unused F# key?

**Comment by kiwijam** [comment]
Thanks!

Moving the window works flawlessly.
Toggling the borders leaves pretty thick borders around the window for me.

**Comment by sylikc** [comment]
> Toggling the borders leaves pretty thick borders around the window for me.

Yeah... for some reason when the title bar goes away, the image gets drawn with a black border... Not quite sure where that's coming from at the moment.  You're seeing black borders right?  Not white or a different color?

**Comment by kiwijam** [comment]
Quick test: The 'border' colour seems to get inherited from

BackgroundColor=33 33 33

in my INI

**Comment by sylikc** [comment]
Right, that's what I meant to say... yeah so it's the background when the border goes away.  I'm going to think the desired behavior is that the window shrinks to the image dimensions... going to be interesting

**Comment by kiwijam** [comment]
Personally, I think I'd want to toggle the titlebar in the INI to have JPEGView start up that way every time. I don't think I'd want to toggle the titlebar while looking at an image, though I suppose some users would.

**Comment by sylikc** [comment]
I see.  Yeah right now what I've found is that when the titlebar is hidden, the window can't be resized.  I still need to fix the image size glitchiness when swapping between both.

I might merge the code to move the window by ALT+LCLICK first and take more time to figure out the titlebar thing

**Comment by 4hench** [comment]
how about disabling the selector tool and only use LCLICK ?

**Comment by sylikc** [comment]
@c-sanchez hotkey to hide titlebar is now SHIFT+F11.  you can modify in KeyMap.txt

**Comment by sylikc** [comment]
@4hench i added an option to disable the default selector mode... but moving will stay as ALT+LCLICK.

**Comment by sylikc** [comment]
the thick borders are still there for the hide-title-bar mode... i can't seem to figure out how to fix that at the moment.  Would the feature still be useful to merge with the slightly thicker borders?

**Comment by sylikc** [comment]
@kiwijam can you test the new build that's just released in this thread?  I think I fixed all the issues and it's almost ready to merge

**Pull request merged**
