### PR TITLE
Basic PSD decoding support

### LINKED ISSUE #29: Add professional formats like PSD
I am a designer, this image viewer is very good for me, I hope to add professional format such as psd and other formats to view, thank you

### PR DESCRIPTION
**Pull request by qbnu**
Format documentation: https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/

Adds support for decoding most common PSDs. If we can't decode them we try to display the embedded JPEG thumbnail instead. The decompression code is from SAIL: https://github.com/HappySeaFox/sail/blob/master/src/sail-codecs/psd/psd.c

### Note
The PSD must have been saved with "Maximize Compatibility" in Photoshop. Otherwise the image data section will not contain the flattened image, in which case we just return the thumbnail.

### Color Modes
Bitmap - Unsupported
Grayscale - Supported
Indexed - Unsupported
RGB - Supported
CMYK - Supported, but colors will be inaccurate. Similar behavior to IMDisplay.
Multichannel - I don't know what this is, but the two files I could find with it worked.
Duotone - Treated as grayscale, which is what the documentation [suggests](https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_pgfId-1037450) and the same behavior as ImageMagick and GIMP.
Lab - Supported if LCMS is present. Otherwise it's treated as grayscale.

### Bit depths
Only 8-bit PSDs are supported.

### Compression Modes
Raw/Uncompressed - I could only find one test file, but it should work.
RLE (run-length encoding) - Supported. Used in the vast majority of PSDs.
ZIP without prediction - Unsupported
ZIP with prediction - Unsupported

### Alpha channels
Only supported for RGB PSDs. I couldn't get them to work with Lab.

### ICC Profiles
Only supported for RGB PSDs.

### EXIF Data
Supported. I added two new fields: "Software" (e.g. Adobe Photoshop CS6, GIMP 2.10.34, etc.) and "Date Time" (used by Photoshop to store modification date).

### PSB (Large Document Format)
Thumbnail only

<details>

<summary>Some useful links</summary>

SAIL's PSD implementation:  
https://github.com/HappySeaFox/sail/blob/master/src/sail-codecs/psd/psd.c  

I looked into using [psd_sdk](https://github.com/MolecularMatters/psd_sdk), but I'm not sure how to build it as a DLL.

ImageMagick's implementation might be useful to look at:  
https://github.com/ImageMagick/ImageMagick/blob/main/coders/psd.c  

Duotone:  
https://gitlab.gnome.org/GNOME/gimp/-/issues/19  
https://gitlab.gnome.org/GNOME/gimp/-/merge_requests/690  

Lab color:  
https://gitlab.gnome.org/GNOME/gimp/-/merge_requests/476  
https://expertphotography.com/lab-color-photoshop/  

Maximize Compatibility/hasRealMergedData:  
https://exiftool.org/forum/index.php?topic=12897.0  

Detecting whether to use alpha channel:  
https://github.com/psd-tools/psd-tools/issues/369  

</details>

Closes #29 and #228

### CODE REVIEW

**Comment by qbnu** [comment]
@sylikc you should upgrade libjxl to a newer commit if they don't release 0.9 soon. 0.8.2 doesn't have the fix for https://github.com/libjxl/libjxl/issues/2251, so right now all HDR images appear too dark.

**Comment by Hrxn** [comment]
Is this already fixed in libjxl?
The linked issue is still open, and nothing is mentioned there..

**Comment by qbnu** [comment]
@Hrxn looks like it
hdr-comp

**Comment by sylikc** [comment]
I'm back (life has been especially busy).  I pulled in the updated libs, but the libjxl issue is still open.  I'm thinking about cutting a release now, there's like tons of changes i've made in the past few months, mostly related to translations, but I really wanted to get the raw stuff in.

**Comment by qbnu** [comment]
@sylikc the version of libjxl you pulled in already has the fix.

**Comment by sylikc** [comment]
@qbnu should I merge this in now or are you still doing some work on it?

**Comment by qbnu** [comment]
@sylikc You can merge it. I want to improve it eventually but it works well enough for now.

**Comment by sylikc** [comment]
I was just looking at that... in ExifTool I think it's just DateTime, but in JPEGView probably hmm... the spec says it's usually the same as DateTimeOriginal, but it's not guaranteed.

We could just use something like "Exif Modified date:"?  When other programs edit and re-save the file, there's no guarantee that that DateTime gets changed...

**Pull request merged**
